ITEM.name = "MP-153"
ITEM.description = "Самозарядное ружьё с трубчатым магазином и газоотводной автоматикой."
ITEM.model = "models/weapons/arc9/darsu_eft/c_mr153.mdl"
ITEM.class = "arc9_eft_mr153"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 2
ITEM.noBusiness = true
ITEM.bDropOnDeath = true
ITEM.twoHanded = true
