ITEM.name = "Milkor M32A1"
ITEM.description = "Шестизарядный револьверный гранатомёт. Использует боеприпасы для гранатомётов."
ITEM.model = "models/weapons/arc9/darsu_eft/c_m32a1.mdl"
ITEM.class = "arc9_eft_m32a1"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 2
ITEM.noBusiness = true
ITEM.bDropOnDeath = true
ITEM.twoHanded = true
