ITEM.name = "AK-74M"
ITEM.description = "Складной полимерный приклад, знакомая автоматика Калашникова и боковое крепление для оптики."
ITEM.model = "models/weapons/arc9/darsu_eft/c_ak100.mdl"
ITEM.class = "arc9_eft_ak74m"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 2
ITEM.noBusiness = true
ITEM.bDropOnDeath = true
ITEM.twoHanded = true
