ITEM.name = "Marlin MXLR"
ITEM.description = "Рычажная винтовка Marlin с трубчатым магазином и ручным перезаряжанием."
ITEM.model = "models/weapons/arc9/darsu_eft/c_mxlr.mdl"
ITEM.class = "arc9_eft_mxlr"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 2
ITEM.noBusiness = true
ITEM.bDropOnDeath = true
ITEM.twoHanded = true
