ITEM.name = "ASh-12"
ITEM.description = "Тяжёлый штурмовой автомат компоновки буллпап для ближних дистанций."
ITEM.model = "models/weapons/arc9/darsu_eft/c_ash12.mdl"
ITEM.class = "arc9_eft_ash12"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 2
ITEM.noBusiness = true
ITEM.bDropOnDeath = true
ITEM.twoHanded = true
