ITEM.name = "Заря"
ITEM.description = "Одноразовая светошумовая граната для дезориентации."
ITEM.model = "models/weapons/arc9/darsu_eft/w_zarya_unthrowed.mdl"
ITEM.class = "arc9_eft_zarya"
ITEM.weaponCategory = "utility"
ITEM.width = 1
ITEM.height = 1
ITEM.noBusiness = true
ITEM.bDropOnDeath = true
ITEM.twoHanded = false
ITEM.isGrenadeARC9 = true
