ITEM.name = "СП-81"
ITEM.description = "Однозарядный сигнальный пистолет. Использует отдельные сигнальные патроны 26×75 мм."
ITEM.model = "models/weapons/arc9/darsu_eft/c_sp81.mdl"
ITEM.class = "arc9_eft_sp81"
ITEM.weaponCategory = "sidearm"
ITEM.width = 2
ITEM.height = 2
ITEM.noBusiness = true
ITEM.bDropOnDeath = true
ITEM.twoHanded = false
