ITEM.name = "AI AXMC"
ITEM.description = "Магазинная снайперская винтовка с продольно-скользящим затвором и модульным шасси."
ITEM.model = "models/weapons/arc9/darsu_eft/c_ai_axmc.mdl"
ITEM.class = "arc9_eft_ai_axmc"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 2
ITEM.noBusiness = true
ITEM.bDropOnDeath = true
ITEM.twoHanded = true
